### ISSUE TITLE
Edit Setting invisible while course creation

### ISSUE THREAD

**Issue by Namgyal-Yolmo** [Veloxnet-LMS/moodle-theme_vxg_boost#3]
While editing a course using the gear icon the first option always greys out making it invisible. I'm using topic format for the course and moodle version is 3.9.1.x

Not sure if this is but but dev can you please confirm. Thanks

**Comment by kashifmian722** [comment]
Hi dear i want to change text in header which is "Moodle Description". can you guide how i can edit or change that text or link. thanks
